### ISSUE TITLE
Config not being displayed as wanted in-game + mcmod changes

### ISSUE THREAD

**Issue by probablykasper** [TeamSpectral/SpectralGuns#25]
The attached picture pretty much explains everything. Look at the title, the list of names and [default: true] being displayed twice.
![screen shot 2015-06-07 at 18 10 42](https://cloud.githubusercontent.com/assets/11315492/8024820/f2a32bc8-0d40-11e5-9b0c-94cf438f3960.png)

The mcmod file can be spiced up. Authors can change to "Sigurd4, SpectralKH, NonExistingName, Beardielover99 and FortuneLessThan3 from Team Spectral".
Credits needs a capitalized T in "Thanks" and C in "Chinese".
URL should be "http://www.planetminecraft.com/mod/spectralguns/".
If possible, we could have the Team Spectral logo be displayed there as well.

**Comment by sigurd4** [comment]
the [default: true] thing is caused by forge and is not something we can do anything about (i'm about 99% sure).
