### ISSUE TITLE
Forge crash

### ISSUE THREAD

**Issue by IDK1432** [TeamSpectral/SpectralGuns#31]
My minecraft forge is crashing(1.8). this is what it says:
---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 6/21/15 10:47 AM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderException: java.lang.NoSuchMethodError: net.minecraft.creativetab.CreativeTabs.<init>(Ljava/lang/String;)V
    at net.minecraftforge.fml.common.LoadController.transition(LoadController.java:163)
    at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:516)
    at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:210)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:414)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:326)
    at net.minecraft.client.main.Main.main(SourceFile:120)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoSuchMethodError: net.minecraft.creativetab.CreativeTabs.<init>(Ljava/lang/String;)V
    at com.spectral.spectral_guns.tabs.TabGeneric.<init>(TabGeneric.java:14)
    at com.spectral.spectral_guns.M$1.<init>(M.java:225)
    at com.spectral.spectral_guns.M.<clinit>(M.java:224)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:249)
    at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:445)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
    at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:505)
    ... 10 more
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.8
    Operating System: Mac OS X (x86_64) version 10.9.5
    Java Version: 1.6.0_65, Apple Inc.
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Apple Inc.
    Memory: 61642712 bytes (58 MB) / 255823872 bytes (243 MB) up to 1060372480 bytes (1011 MB)
    JVM Flags: 5 total; -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.10 FML v8.0.127.1103 3 mods loaded, 3 mods active
    mcp{9.05} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed
    FML{8.0.127.1103} [Forge Mod Loader](fml-1.8-8.0.127.1103.jar) Unloaded->Constructed
    spectralguns{1.2.5} [Spectral Guns]([Forge 1.8] SpectralGuns 1.2.5.jar) Unloaded->Errored
    Loaded coremods (and transformers): 
    GL info: ' Vendor: 'NVIDIA Corporation' Version: '2.1 NVIDIA-8.24.16 310.90.9.05f01' Renderer: 'NVIDIA GeForce 9400 OpenGL Engine'

What is going On? Is it an issue with spectral guns?

**Comment by sigurd4** [comment]
try to use the minecraft-forge version 11.14.1.1334 (the stable one). you are using fml 8.0.127.1103.

**Comment by sigurd4** [comment]
i'll close this once you report back, just to be sure

**Comment by IDK1432** [comment]
It works! Except I made a fireball gun with a laser pointer scope and a scatter barrel, and Minecraft crashes... Heres the report.

`---- Minecraft Crash Report ----`
`// Hi. I'm Minecraft, and I'm a crashaholic.`
`Time: 6/25/15 2:42 PM`
`Description: Rendering entity in world`
`java.lang.NullPointerException: Rendering entity in world`
`at net.minecraft.client.renderer.entity.RenderFireball.func_76986_a(SourceFile:36)`
`at net.minecraft.client.renderer.entity.RenderFireball.func_76986_a(SourceFile:13)`
`at net.minecraft.client.renderer.entity.RenderManager.func_147939_a(RenderManager.java:370)`
`at net.minecraft.client.renderer.entity.RenderManager.func_147936_a(RenderManager.java:327)`
`at net.minecraft.client.renderer.entity.RenderManager.func_147937_a(RenderManager.java:294)`
`at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:631)`
`at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1297)`
`at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1210)`
`at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1035)`
`at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)`
`at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:345)`
`at net.minecraft.client.main.Main.main(SourceFile:120)`
`at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)`
`at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)`
`at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)`
`at java.lang.reflect.Method.invoke(Method.java:597)`
`at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)`
`at net.minecraft.launchwrapper.Launch.main(Launch.java:28)`
`A detailed walkthrough of the error, its code path and all known details is as follows:`
`---------------------------------------------------------------------------------------`
`-- Head --`
`Stacktrace:`
`at net.minecraft.client.renderer.entity.RenderFireball.func_76986_a(SourceFile:36)`
`at net.minecraft.client.renderer.entity.RenderFireball.func_76986_a(SourceFile:13)`
`-- Entity being rendered --`
`Details:`
`Entity Type: SmallFireball (net.minecraft.entity.projectile.EntitySmallFireball)`
`Entity ID: 12594`
`Entity Name: Small Fireball`
`Entity's Exact location: -166.50, 74.50, 247.66`
`Entity's Block location: -167.00,74.00,247.00 - World: (-167,74,247), Chunk: (at 9,4,7 in -11,15; contains blocks -176,0,240 to -161,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)`
`Entity's Momentum: -0.02, -0.05, 0.08`
`Entity's Rider: ~~ERROR~~ NullPointerException: null`
`Entity's Vehicle: ~~ERROR~~ NullPointerException: null`
`-- Renderer details --`
`Details:`
`Assigned renderer: net.minecraft.client.renderer.entity.RenderFireball@51938132`
`Location: 0.20,1.50,0.16 - World: (0,1,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)`
`Rotation: 242.9973`
`Delta: 0.71661115`
`Stacktrace:`
`at net.minecraft.client.renderer.entity.RenderManager.func_147939_a(RenderManager.java:370)`
`at net.minecraft.client.renderer.entity.RenderManager.func_147936_a(RenderManager.java:327)`
`at net.minecraft.client.renderer.entity.RenderManager.func_147937_a(RenderManager.java:294)`
`at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:631)`
`at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1297)`
`at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1210)`
`-- Affected level --`
`Details:`
`Level name: MpServer`
`All players: 1 total; [EntityPlayerSP['1432MineTrains'/5314, l='MpServer', x=-166.70, y=73.00, z=247.50]]`
`Chunk stats: MultiplayerChunkCache: 169, 169`
`Level seed: 0`
`Level generator: ID 00 - default, ver 1. Features enabled: false`
`Level generator options:`
`Level spawn location: -160.00,64.00,256.00 - World: (-160,64,256), Chunk: (at 0,4,0 in -10,16; contains blocks -160,0,256 to -145,255,271), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)`
`Level time: 8508 game time, 8508 day time`
`Level dimension: 0`
`Level storage version: 0x00000 - Unknown?`
`Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)`
`Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false`
`Forced entities: 53 total; [EntityPlayerSP['1432MineTrains'/5314, l='MpServer', x=-166.70, y=73.00, z=247.50], EntityItem['item.item.foodMush'/10805, l='MpServer', x=-166.84, y=74.00, z=250.50], EntityBat['Bat'/9954, l='MpServer', x=-179.25, y=46.10, z=238.16], EntityCow['Cow'/5185, l='MpServer', x=-147.50, y=74.00, z=308.50], EntityCow['Cow'/5184, l='MpServer', x=-148.50, y=75.00, z=306.50], EntityRabbit['Rabbit'/5208, l='MpServer', x=-92.66, y=71.00, z=221.34], EntityRabbit['Rabbit'/5209, l='MpServer', x=-92.50, y=71.00, z=272.50], EntityRabbit['Rabbit'/5210, l='MpServer', x=-93.66, y=71.00, z=269.34], EntityRabbit['Rabbit'/5206, l='MpServer', x=-88.50, y=71.00, z=220.50], EntityRabbit['Rabbit'/5207, l='MpServer', x=-88.66, y=71.00, z=221.34], EntityCow['Cow'/5163, l='MpServer', x=-145.19, y=79.00, z=294.16], EntityCow['Cow'/5162, l='MpServer', x=-153.47, y=73.00, z=287.53], EntityCow['Cow'/5167, l='MpServer', x=-152.50, y=77.00, z=299.50], EntityCow['Cow'/5166, l='MpServer', x=-153.50, y=78.00, z=301.50], EntityCow['Cow'/5165, l='MpServer', x=-156.47, y=83.00, z=288.50], EntityCow['Cow'/5164, l='MpServer', x=-157.56, y=83.00, z=288.50], EntityPig['Pig'/5178, l='MpServer', x=-136.47, y=77.00, z=236.53], EntityPig['Pig'/5179, l='MpServer', x=-166.56, y=69.00, z=214.94], EntityCow['Cow'/5182, l='MpServer', x=-151.50, y=77.00, z=304.50], EntityCow['Cow'/5183, l='MpServer', x=-151.50, y=77.00, z=307.50], EntityPig['Pig'/5180, l='MpServer', x=-136.16, y=78.00, z=236.13], EntityPig['Pig'/5181, l='MpServer', x=-135.09, y=71.00, z=235.16], EntityCow['Cow'/5168, l='MpServer', x=-154.56, y=77.00, z=297.50], EntityCow['Cow'/5169, l='MpServer', x=-153.19, y=77.00, z=297.50], EntityPig['Pig'/5129, l='MpServer', x=-229.50, y=67.00, z=216.50], EntityPig['Pig'/5128, l='MpServer', x=-227.50, y=67.00, z=217.81], EntityPig['Pig'/5131, l='MpServer', x=-202.50, y=75.00, z=173.50], EntityPig['Pig'/5130, l='MpServer', x=-230.50, y=67.00, z=218.50], EntityPig['Pig'/5133, l='MpServer', x=-207.50, y=70.00, z=172.50], EntityPig['Pig'/5132, l='MpServer', x=-206.50, y=74.00, z=171.50], EntityPig['Pig'/5134, l='MpServer', x=-208.44, y=71.00, z=175.38], EntityPig['Pig'/5123, l='MpServer', x=-222.50, y=68.00, z=188.50], EntityPig['Pig'/5125, l='MpServer', x=-221.56, y=67.00, z=192.78], EntityPig['Pig'/5124, l='MpServer', x=-219.50, y=66.00, z=192.50], EntityPig['Pig'/5127, l='MpServer', x=-227.50, y=67.00, z=216.19], EntityPig['Pig'/5126, l='MpServer', x=-220.19, y=67.00, z=191.16], EntityCow['Cow'/5151, l='MpServer', x=-184.16, y=74.00, z=324.19], EntityRabbit['Rabbit'/5139, l='MpServer', x=-204.50, y=76.00, z=177.50], EntityRabbit['Rabbit'/5141, l='MpServer', x=-204.31, y=75.02, z=172.16], EntitySmallFireball['Small Fireball'/12594, l='MpServer', x=-166.50, y=74.50, z=247.66], EntitySmallFireball['Small Fireball'/12595, l='MpServer', x=-166.50, y=74.50, z=247.66], EntitySmallFireball['Small Fireball'/12592, l='MpServer', x=-166.50, y=74.50, z=247.66], EntitySmallFireball['Small Fireball'/12593, l='MpServer', x=-166.50, y=74.50, z=247.66], EntitySmallFireball['Small Fireball'/12587, l='MpServer', x=-166.50, y=74.50, z=247.66], EntitySmallFireball['Small Fireball'/12591, l='MpServer', x=-166.50, y=74.50, z=247.66], EntitySmallFireball['Small Fireball'/12590, l='MpServer', x=-166.50, y=74.50, z=247.66], EntitySmallFireball['Small Fireball'/12589, l='MpServer', x=-166.50, y=74.50, z=247.66], EntitySmallFireball['Small Fireball'/12588, l='MpServer', x=-166.50, y=74.50, z=247.66], EntityPig['Pig'/5117, l='MpServer', x=-235.56, y=63.00, z=311.50], EntityPig['Pig'/5116, l='MpServer', x=-245.50, y=70.00, z=309.81], EntityPig['Pig'/5119, l='MpServer', x=-234.19, y=63.00, z=311.50], EntityPig['Pig'/5118, l='MpServer', x=-234.50, y=64.00, z=309.50], EntityItem['item.tile.doublePlant.paeonia'/10609, l='MpServer', x=-227.31, y=64.00, z=266.75]]`
`Retry entities: 0 total; []`
`Server brand: fml,forge`
`Server type: Integrated singleplayer server`
`Stacktrace:`
`at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:351)`
`at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2502)`
`at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:367)`
`at net.minecraft.client.main.Main.main(SourceFile:120)`
`at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)`
`at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)`
`at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)`
`at java.lang.reflect.Method.invoke(Method.java:597)`
`at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)`
`at net.minecraft.launchwrapper.Launch.main(Launch.java:28)`
`-- System Details --`
`Details:`
`Minecraft Version: 1.8`
`Operating System: Mac OS X (x86_64) version 10.9.5`
`Java Version: 1.6.0_65, Apple Inc.`
`Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Apple Inc.`
`Memory: 321517264 bytes (306 MB) / 630841344 bytes (601 MB) up to 1060372480 bytes (1011 MB)`
`JVM Flags: 5 total; -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M`
`IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95`
`FML: MCP v9.10 FML v8.0.99.99 Minecraft Forge 11.14.3.1480 4 mods loaded, 4 mods active`
`States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored`
`UCHIJAAAAAAAAA mcp{9.05} [Minecraft Coder Pack] (minecraft.jar)`
`UCHIJAAAAAAAAA FML{8.0.99.99} [Forge Mod Loader] (forge-1.8-11.14.3.1480.jar)`
`UCHIJAAAAAAAAA Forge{11.14.3.1480} [Minecraft Forge] (forge-1.8-11.14.3.1480.jar)`
`UCHIJAAAAAAAAA spectralguns{1.2.5} [Spectral Guns] ([Forge 1.8] SpectralGuns 1.2.5.jar)`
`Loaded coremods (and transformers):`
`GL info: ' Vendor: 'NVIDIA Corporation' Version: '2.1 NVIDIA-8.24.16 310.90.9.05f01' Renderer: 'NVIDIA GeForce 9400 OpenGL Engine'`
`Launched Version: 1.8-Forge11.14.3.1480`
`LWJGL: 2.9.2`
`OpenGL: NVIDIA GeForce 9400 OpenGL Engine GL version 2.1 NVIDIA-8.24.16 310.90.9.05f01, NVIDIA Corporation`
`GL Caps: Using GL 1.3 multitexturing.`
`Using GL 1.3 texture combiners.`
`Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.`
`Shaders are available because OpenGL 2.1 is supported.`
`VBOs are available because OpenGL 1.5 is supported.`
`Using VBOs: No`
`Is Modded: Definitely; Client brand changed to 'fml,forge'`
`Type: Client (map_client.txt)`
`Resource Packs: []`
`Current Language: English (US)`
`Profiler Position: N/A (disabled)`

**Comment by sigurd4** [comment]
how strange. again, though: i'd recommend using forge 11.14.1.1334. you are using 11.14.3.1480. just try it

**Comment by probablykasper** [comment]
Tried to replicate the issue, but it seemed to work.

**Comment by IDK1432** [comment]
I used auto trigger and fireball ammo JSYK (Just So You Know)

**Comment by probablykasper** [comment]
@sigurd4 What we _could_ do about that, is make it an incompatible recipe.

**Comment by probablykasper** [comment]
@IDK1432 You couldn't try doing the same with the latest Forge version?

**Comment by IDK1432** [comment]
JSYK, I use a Mac, FYI. So I may be a version or two behind

**Comment by IDK1432** [comment]
Forge versions, I mean

**Comment by probablykasper** [comment]
@IDK1432 Both versions are at the same version, but they don't specify if it's for OS X or not; They have an "Installer-Win" for Windows, and "Installer" which is for both OS X and Linux. Download at http://files.minecraftforge.net/.

**Comment by IDK1432** [comment]
Don't judge :unamused:

**Comment by probablykasper** [comment]
@IDK1432 What am I doing wrong?

**Comment by probablykasper** [comment]
@IDK1432 Could it be a problem with your PC? You're not running the latest OS X version - that shouldn't be a problem though - but what version of Java do you have? The crash report says Java 6.

**Comment by sigurd4** [comment]
java 7 should work btw. 8 could also work.

**Comment by probablykasper** [comment]
@IDK1432 We're just trying to help you! But we need your help in order to do that.
