### ISSUE TITLE
Quick change to Assembly Station (High priority)

### ISSUE THREAD

**Issue by probablykasper** [TeamSpectral/SpectralGuns#56]
The notification appearing once you're doing something wrong (Like putting a gun into the station without a wrench), the notification appearing should last longer. I can't even read it without spamming buttons.

@sigurd4 @Beardielover

**Comment by sigurd4** [comment]
i fixed this, kh! remember??

**Comment by probablykasper** [comment]
@sigurd4 Ohh, sorry, my fault!
