### ISSUE TITLE
Gun workbench: crafting guns

### ISSUE THREAD

**Issue by probablykasper** [TeamSpectral/SpectralGuns#6]
Lets you create guns.

**Comment by probablykasper** [comment]
Example GUI by @sigurd4:
![upload_2014-12-22_at_2 10 55_pm](https://cloud.githubusercontent.com/assets/11315492/6489357/fd2fa4c4-c29d-11e4-9960-b906c69465c9.png)

**Comment by sigurd4** [comment]
going to work on this after the 1.1.1 patch. i've just recently educated myslef on how to do guis.

**Comment by sigurd4** [comment]
any ideas on what we could call the workbench? here are some of my suggestions (in addition to the obvious "gun workbench" of course), being a combination of two phrases:

first word:
- gun
- weapon
- firearm
- firepower
- arms

second word:
- table
- workbench
- factory
- assembly table
- assembler
- asembly line
- crafter
- station

any other ideas? which one do you guys think is the best?

**Comment by sigurd4** [comment]
i think i quite like "gun assembly station" or something like that

**Comment by probablykasper** [comment]
For now, gun should be the first word, as it's only used for guns. May be extended in the future tho. Station and/or something with assembly/-er seems nice as secondary word to me.
